stages:
  - test
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Java version:"
  - java -version
  - echo "Using Maven version:"
  - mvn -version

unit_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/

bdd_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    when: always
    reports:
      junit: target/cucumber-reports/TEST-*.xml
    paths:
      - target/cucumber-reports/

build_jar:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

# Uncomment and configure the deploy stage if needed
# deploy_to_server:
#   stage: deploy
#   only:
#     - main
#   script:
#     - echo "Deploying application..."
#     - scp target/*.jar user@your-server:/path/to/deploy/
